image: docker:latest

services:
  - docker:dind

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

stages:
  - build
  # - test
  - deploy

before_script:
  - export MAVEN_USER_HOME=`pwd`/.maven

build auto24:
  stage: build
  cache:
    paths:
      - .mvn/wrapper
      - .mvn/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - auto24
  script:
    - mvn $MAVEN_CLI_OPTS compile

deploy database:
  stage: deploy
  only:
    refs:
      - master
  tags:
    - auto24
  script:
    - docker-compose -f docker/docker-compose.yml up



